config/routes.rb
VQuotes::Application.routes.draw do
  get "home/show"
  get "home/create"
  get "home/search"
  get "home/mine"

  get "v_quote/show"
  get "v_quote/new"
  get "v_quote/create"
  get "v_quote/delete"
  get "v_quote/autocomplete"

  match 'video' => "v_quote#show"
  match 'new' => "v_quote#new"
  match 'mine' => "home#mine"
  match 'quoto/:id' => "v_quote#show"

  resources :v_quote
  resources :home

  match 'auth/facebook/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

  root :to => 'home#show'

end

app/models/movie_titles.rb
class MovieTitles < ActiveRecord::Base
  self.table_name = "titles_movies_series"
  # attr_accessible :title, :body
end

app/models/titles.rb
class Titles < ActiveRecord::Base
  # attr_accessible :title, :body
  self.table_name = 'titles_movies_series'
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :fname, :lname, :name, :oauth_expires_at, :oauth_token, :provider, :uid
  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.email = auth.info.email
      user.fname = auth.info.first_name
      user.lname = auth.info.last_name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/models/v_quote.rb
class VQuote < ActiveRecord::Base
  attr_accessible :vDescription, :vEnd, :vStart, :vTitle, :youtubeId

  ORIGIN = "http://www.vquoto.com"
  YOUTUBE_VIDEO_URL = "https://www.youtube.com/watch?v=";
  YOUTUBE_IMAGE_URL = "https://img.youtube.com/vi/";
  YOUTUBE_IMAGE_ID = "/0.jpg";

  def youtube_url
    return YOUTUBE_VIDEO_URL + youtubeId;
  end

  def image_url
    return YOUTUBE_IMAGE_URL + youtubeId + YOUTUBE_IMAGE_ID;
  end

  def sliced_url

    # Create a configurable youtube class.
    return "https://www.youtube.com/v/" + 
      youtubeId + get_youtube_configs
  end
  
  def embed_url

    # Create a configurable youtube class.
    return "https://www.youtube.com/embed/" + 
      youtubeId + get_youtube_configs
  end


  private 

  def get_youtube_configs
    return "?start=" + vStart.to_s + "&end=" + vEnd.to_s + 
      "&autoplay=1&controls=0&showinfo=0&iv_load_policy=3&rel=0&modestBranding=1&version=3&enablejsapi=1&origin=" + ORIGIN + "&wmode=opaque";
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    @v_quotes = VQuote.all
    @loadVideo = nil

    if (params[:id] != nil) 
      @loadVideo = VQuote.find_by_id(params[:id])
    end

  end

  def viewer
  end

  def search
    puts params
    @v_quotes = VQuote.where("movieName LIKE ?", params[:key] + "%")
    respond_to do |format|
      format.json {
      render :json => render_to_string(:layout => false, :action => "_gallery", :formats => :html, :collection =>  @v_quotes)
    }
 end

  end

  def mine
    if current_user
      @v_quotes = VQuote.where(:userId => current_user.id)
      puts current_user
      puts @v_quotes
      render 'show'
    else 
      redirect_to "/"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/v_quote_controller.rb
class VQuoteController < ApplicationController
  def show
    @video = VQuote.find_by_id(params[:id])
  end

  def new
    if !current_user
      redirect_to "/"
    end
  end

  def create
    #TODO : Validate params

    if current_user
      if params[:youtubeId] == nil
        redirect_to "/"
      else
      vq = VQuote.new

      puts params
      vq.vTitle = params[:vTitle]
      vq.youtubeId = params[:youtubeId]
      vq.vStart = params[:vStart]
      vq.vEnd = params[:vEnd]
      vq.movieName = params[:mName]
      vq.actorName = params[:aName]
      vq.movieId = params[:mId]
      vq.userId = current_user.id
      vq.save
     
      respond_to do |format|
        format.json {
          render :json => vq.id
      }
    end
    end
    end

  end

  def autocomplete
    @titles = MovieTitles.where("title LIKE ?", params[:searchKey] + "%").limit(10)
    respond_to do |format|
      format.json {
        render :json => @titles.to_json
      }
    end
  end

  def delete
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/home_helper.rb
module HomeHelper
  def redirect_to_root
    redirect_to "/"
  end
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/v_quote_helper.rb
module VQuoteHelper
end

app/views/home/_gallery.html.erb
	<div id="galleryContainer">
  		<%= render partial: "v_quote", collection: @v_quotes %>
	</div>

app/views/home/_v_quote.html.erb
<div class="videoContainer">
  <div class="vImageContainer">
    <img class="vImage" src ="https://img.youtube.com/vi/<%= v_quote.youtubeId %>/0.jpg" data-id="<%= v_quote.id %>"  data-youtubeId="<%= v_quote.youtubeId %>" data-start="<%= v_quote.vStart %>" data-end="<%= v_quote.vEnd %>" data-title="<%= v_quote.vTitle %>" data-mName="<%= v_quote.movieName %>" data-aName="<%= v_quote.actorName %>">
  </div>
  <div class="vInfoContainer"  data-id="<%= v_quote.id %>" data-youtubeId="<%= v_quote.youtubeId %>" data-start="<%= v_quote.vStart %>" data-end="<%= v_quote.vEnd %>" data-title="<%= v_quote.vTitle %>" data-mName="<%= v_quote.movieName %>" data-aName="<%= v_quote.actorName %>">
    <div class="vInfoTitle" >
      <%= v_quote.vTitle %>
    </div>
    <div class="vInfoOther" >
      <%= v_quote.movieName %>
    </div>
  </div>
</div>

app/views/home/_viewer.html.erb
<%= javascript_include_tag "viewer" %>
<script>
      function onYouTubeIframeAPIReady() {
        window.viewerPlayer = new YT.Player("viewerPlayer", {
          height: '100%',
          width: '100%',
          events: {
            'onReady': onPlayerReady,
            'onStateChange': onPlayerStateChange
          }
        });

      }

      function onPlayerReady(event) {
        var loadVideo = $("#loadVideo")[0];
        if (typeof loadVideo !== "undefined") {
          var $loadVideo = $(loadVideo);
          var data = {
            'id' : $loadVideo.data("id"),
            'youtubeId' :  $loadVideo.data("youtubeid"),
            'start' : $loadVideo.data("start"),
            'end' : $loadVideo.data("end"),
            'title' : $loadVideo.data("title"),
            'mName' : $loadVideo.data("mname"),
            'aName' : $loadVideo.data("aname"),
            'suggestedQuality': 'large'
          };
          $("#viewer").viewer("loadVideo", data);
        } else {
          $("#infoContainer").hide();
        }
      }

      var done = false;
      function onPlayerStateChange(event) {
        if (event.data == YT.PlayerState.PLAYING && !done) {
          done = true;
        }
      }
      function stopVideo() {
        player.stopVideo();
      }
</script>

<div id="viewer">
  <div id="playerContainer">
    <div id="viewerPlayer"></div>
  </div>
  <div id="infoContainer" style="display:none">
    <div id="copyLinkLabel" class="viewerText" >Copy paste this link</div>
    <input id="copyLink" class = "formText" value="" />
    <div id="quoteInfo">
      <div id="quoteTitle" class="viewerText" ></div>
      <div id="quoteMovie"  class="viewerText"></div>
      <div id="quoteActor"  class="viewerText"></div>
    </div>

  </div>
</div>

app/views/home/show.html.erb
<div id="searchDiv" >
    <input type="text" id="searchBox" placeholder="Movie Name" />
  </div>
<div id="gallery">
  <%= render "gallery" %>
</div>
<%= render "viewer" %>
<% if @loadVideo %>
 <div id="loadVideo"  data-id="<%= @loadVideo.id %>" data-youtubeid="<%= @loadVideo.youtubeId %>" data-start="<%= @loadVideo.vStart %>" data-end="<%= @loadVideo.vEnd %>" data-title="<%= @loadVideo.vTitle %>" data-mname="<%= @loadVideo.movieName %>" data-aname="<%= @loadVideo.actorName %>">
<% end %>

app/views/home/viewer.html.erb
<% content_for :viewer do %>
  Viewer
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VQuoto</title>
  <link rel="shortcut icon" href="/assets/logo.ico">
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "jquery_min" %>
  <%= javascript_include_tag "facebook" %>
  <%= javascript_include_tag "v_quote" %>
  <%= javascript_include_tag "gallery" %>
  <%= javascript_include_tag "main" %>
  <%= csrf_meta_tags %>
  <!--
  <meta property="og:site_name" content="VQuoto">
  <meta property="og:url" content="http://www.vquoto.com">
  <meta property="fb:app_id" content="1377638272475800"/>
  <meta property="og:type" content="website"/>
  <meta property="og:title" content="VQuoto"/>
  -->
  <meta property="og:site_name" content="VQuoto">

  <% if @video %>
  <meta property="og:title" content="<%= @video.vTitle %>">
  <meta property="og:type" content="video.movie">
  <meta property="og:image" content="<%= @video.image_url %>">
  <meta name="description" content="<%= @video.movieName %> - <%= @video.actorName %>">
  <meta property="og:description" content="VQuoto - make your posts entertaining!">
  <meta property="og:video" content="<%= @video.sliced_url %>">
  <meta property="og:video:type" content="application/x-shockwave-flash">
  <meta property="og:video" content="<%= @video.embed_url %>">
  <meta property="og:video:type" content="video/mp4">
  <% end %>
</head>
<body>
  <div id="fb-root"></div>
  <div id="container">
    <div id="header">
      <div id="logoContainer">
        <a id="logoTitle">VQuoto</a>
        <div class="fb-like navLinks" data-colorscheme="light" data-layout="standard" data-action="like" data-show-faces="false" data-send="false"></div>
      </div>
  <div id="user_nav">
    
    <% if current_user %>
      <a id="createButton" class="greenButton" href="/new">CREATE A QUOTE</a>
      <a id="myhome" class="navLinks" href="/">Home</a>
      <a id="mySlices" class="navLinks" href="/mine ">Mine</a>
      <div id="user_name"><%= current_user.name %></div>
      <a id="signOutButton" href=<%=signout_path %> ></a>
    <% else %>    	
      <div class="headerText">To create a new quote, </div>
      <a href="/auth/facebook" id="signInButton" class="greenButton" >LOGIN WITH FACEBOOK</a>
      
    <% end %>
  </div>
  
 
  </div>

  <%= yield %>



</div>

</body>
</html>

app/views/v_quote/delete.html.erb
<h1>VQuote#delete</h1>
<p>Find me in app/views/v_quote/delete.html.erb</p>

app/views/v_quote/new.html.erb
<%= javascript_include_tag "youtube_player" %>
<div id="newForm">
  <div id="loadFormContainer">
    <div id="loadForm">
      <input id="youtubeUrl" class="formText" type="text" name="youtubeUrl" placeholder="http://www.youtube.com/watch?v=YOUTUBE_ID">
      <input id="startTime" class="formText" type="text" name="startTime" placeholder="start [0:00]">
      <input id="endTime" class="formText" type="text" name="endTime" placeholder="end [0:00]">
      <a id="loadButton" class="greenButton" href="#">Play</a>
    </div>
  </div>
  <div id="notification"> </div>
  <iframe id="createVideoPlayer" type="text/html" width="780px" height="380px" frameborder="0" ></iframe>
  <div id="uploadFormContainer">
    <div id="uploadForm">
      <input id="title" class="formText" type="text" name="startTime" placeholder="Short Description*">
      <input id="movieName" class="formText" type="text" name="startTime" placeholder="Movie Name*">
      <input id="actorName" class="formText" type="text" name="endTime" placeholder="Actor Name">
      <a id="uploadButton" class="greenButton" href="#">Save</a>
    </div>
  </div>
</div>

app/views/v_quote/show.html.erb
	<div style="text-align: center;" id="showPlayerContainer">
        <iframe id="theVideo" class="youtube-player" type="text/html" width="100%" height="100%" src="<%= @video.embed_url %>" frameborder="0" allowfullscreen="true"></iframe>
        </div>